name: Giraffe
main: me.sergivb01.giraffe.Giraffe
version: SNAPSHOT-1.3
author: sergivb01
description: Giraffe plugin
depend: [Construct]
commands:
  syncdata:
  sc:
    aliases: [staffchat]
    description: Private chat across servers for staff members
  report:
    description: Allows users to report a player
  request:
    aliases: [helpop]
    description: Allows users to request help
  staffserver:
    description: Allows staff to teleport to another server
  toggletab:
    description: Toggles player tab
  findlag:
    aliases: [fl]
    description: Helper to find server lag